Make container compatible with new Daspanel init/configuration system

diff --git a/rootfs/etc/services.d/gunicorn/run b/rootfs/etc/services.d/gunicorn/run
--- a/rootfs/etc/services.d/gunicorn/run
+++ b/rootfs/etc/services.d/gunicorn/run
@@ -1,5 +1,13 @@
 #!/usr/bin/with-contenv sh
 
+# Installation UUID must be informed
+if [ -z "$DASPANEL_SYS_UUID" ]; then
+    echo "***"
+    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
+    echo "***"
+    exit 1
+fi
+
 # Change dir to app root dir
 if [ ! -z "$GUNICORN_APP_DIR" ]; then
     cd ${GUNICORN_APP_DIR}
